export enum Visibility {
  PUBLIC,
  PRIVATE,
}

export enum JobStatus {
  PENDING = 0, // 0%
  DEPOLYING_SAAS3_DRUNTIME,
  CONFIGURING_DRUNTIME,
  DEPLOYING_PHALA_TRANSACTOR,
  CONFIGURING_PHALA_TRANSACTOR,
  DEPLOYING_PHALA_ANCHOR,
  CONFIGURING_PHALA_ANCHOR,
  ERROR,
  DONE, // 100%
}
