export enum Visibility {
  PUBLIC,
  PRIVATE,
}

export enum JobStatus {
  PENDING = 0, // 0%
  DEPLOYING_PHALA_ANCHOR,
  PHALA_ANCHOR_DEPOLYED,
  CONFIGURING_PHALA_ANCHOR,
  PHALA_ANCHOR_CONFIGED,
  DEPLOYING_PHALA_TRANSACTOR,
  PHALA_TRANSACTOR_DEPLOYED,
  CONFIGURING_PHALA_TRANSACTOR,
  PHALA_TRANSACTOR_CONFIGED,
  DEPOLYING_SAAS3_DRUNTIME,
  SAAS3_DRUNTIME_DEPLOYED,
  CONFIGURING_DRUNTIME,
  DRUNTIME_CONFIGED,
  ERROR,
  DONE, // 100%
}
